In [1]:
import cv2
import numpy as np 
import sys
import pickle

# mouse callback function to select the ROIs
def draw_rectangle(event,x,y,flags,param):

    global pt1,pt2,topLeft_clicked,botRight_clicked

    # get mouse click
    if event == cv2.EVENT_LBUTTONDOWN:

        if topLeft_clicked == True and botRight_clicked == True:
            topLeft_clicked = False
            botRight_clicked = False
            pt1 = (0,0)
            pt2 = (0,0)

        if topLeft_clicked == False:
            pt1 = (x,y)
            topLeft_clicked = True
            
        elif botRight_clicked == False:
            pt2 = (x,y)
            botRight_clicked = True

        
# Haven't drawn anything yet!
entrance_pts=list()#np.zeros(2)# 2 because there are 2 points to identify each region
pt1 = (0,0)
pt2 = (0,0)
topLeft_clicked = False
botRight_clicked = False

cap = cv2.VideoCapture(0) # add a 0 to connect to the camera 

# Create a named window for connections
cv2.namedWindow('Entrance')

# Bind draw_rectangle function to mouse cliks
cv2.setMouseCallback('Entrance', draw_rectangle) 


while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    if topLeft_clicked:
        cv2.circle(frame, center=pt1, radius=5, color=(0,0,255), thickness=-1)
        
    #drawing rectangle
    if topLeft_clicked and botRight_clicked:
        cv2.rectangle(frame, pt1, pt2, (0, 0, 255), 2)
        
        pts=list([pt1, pt2])
        entrance_pts.append(pts)#np.vstack((entrance_pts, pts))
        
    # Display the resulting frame
    cv2.imshow('Entrance', frame)

    # This command let's us quit with the "q" button on a keyboard.
    # Simply pressing X on the window won't work!
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()
entrance_pts=np.unique(entrance_pts,axis=0)
print(entrance_pts)
pickle.dump(entrance_pts, sys.stdout) 

[[[158 137]
  [208 142]]

 [[163 300]
  [239 349]]

 [[207 143]
  [155 184]]

 [[208 176]
  [275 220]]

 [[341 153]
  [390 191]]

 [[360 190]
  [288 150]]]
�cnumpy.core.multiarray
_reconstruct
qcnumpy
ndarray
qK�qCbq�qRq(KKKK�qcnumpy
dtype
qXi4q���q	Rq
tqb.

In [3]:
cap.release()
cv2.destroyAllWindows()

array([186, 237])

In [4]:
[pt1, pt2]

[(360, 190), (288, 150)]

In [5]:
pts=list(pts)

In [6]:
pts.append(pts)

pts

In [7]:
pts

[(360, 190), (288, 150), [...]]

In [24]:
a=list()

In [25]:
a


[]

In [11]:
import cv2 as cv
import numpy as np 
import sys
import pickle
import time

# Enable the optimized code paths
cv.setUseOptimized(True)

# mouse callback function to select the ROIs
def draw_rectangle(event,x,y,flags,param):

    global pt1,pt2,topLeft_clicked,botRight_clicked

    # get mouse click
    if event == cv2.EVENT_LBUTTONDOWN:

        if topLeft_clicked == True and botRight_clicked == True:
            topLeft_clicked = False
            botRight_clicked = False
            pt1 = (0,0)
            pt2 = (0,0)

        if topLeft_clicked == False:
            pt1 = (x,y)
            topLeft_clicked = True
            
        elif botRight_clicked == False:
            pt2 = (x,y)
            botRight_clicked = True

        
# Haven't drawn anything yet!
entrance_pts=list()#np.zeros(2)# 2 because there are 2 points to identify each region
pt1 = (0,0)
pt2 = (0,0)
topLeft_clicked = False
botRight_clicked = False

cap = cv2.VideoCapture(0) # add a 0 to connect to the camera 

# Create a named window for connections
cv2.namedWindow('Entrance')

# Bind draw_rectangle function to mouse cliks
cv2.setMouseCallback('Entrance', draw_rectangle) 

# Start the timer
start = time.time()

while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Reduce the image size by half
    frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)

    # Convert the image to grayscale
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    if topLeft_clicked:
        cv2.circle(frame, center=pt1, radius=5, color=(0,0,255), thickness=-1)
        
    #drawing rectangle
    if topLeft_clicked and botRight_clicked:
        cv2.rectangle(frame, pt1, pt2, (0, 0,255), 2)
        
        pts=list([pt1, pt2])
        entrance_pts.append(pts)#np.vstack((entrance_pts, pts))
        
    # Display the resulting frame
    cv2.imshow('Entrance', frame)

    # This command let's us quit with the "q" button on a keyboard.
    # Simply pressing X on the window won't work!
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Stop the timer
end = time.time()

# Calculate the execution time
print(f"Execution time: {end - start} seconds")

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()
entrance_pts=np.unique(entrance_pts,axis=0)
print(entrance_pts)
pickle.dump(entrance_pts, sys.stdout) 


Execution time: 9.739949703216553 seconds
[[[126  84]
  [181 123]]

 [[146 160]
  [230 197]]

 [[227  76]
  [261 117]]]
�cnumpy.core.multiarray
_reconstruct
qcnumpy
ndarray
qK�qCbq�qRq(KKKK�qcnumpy
dtype
qXi4���q	Rq
tqb.<qNNNJ����J����Ktqb�C0~T�{�����Luq

In [13]:
import cv2
import numpy as np 
import sys
import pickle
import time

# Enable the optimized code paths
cv.setUseOptimized(True)

# mouse callback function to select the ROIs
def draw_rectangle(event,x,y,flags,param):

    global pt1,pt2,topLeft_clicked,botRight_clicked

    # get mouse click
    if event == cv2.EVENT_LBUTTONDOWN:

        if topLeft_clicked == True and botRight_clicked == True:
            topLeft_clicked = False
            botRight_clicked = False
            pt1 = (0,0)
            pt2 = (0,0)

        if topLeft_clicked == False:
            pt1 = (x,y)
            topLeft_clicked = True
            
        elif botRight_clicked == False:
            pt2 = (x,y)
            botRight_clicked = True

        
# Haven't drawn anything yet!
entrance_pts=list()#np.zeros(2)# 2 because there are 2 points to identify each region
pt1 = (0,0)
pt2 = (0,0)
topLeft_clicked = False
botRight_clicked = False

cap = cv2.VideoCapture(0) # add a 0 to connect to the camera 

# Create a named window for connections
cv2.namedWindow('Entrance')

# Bind draw_rectangle function to mouse cliks
cv2.setMouseCallback('Entrance', draw_rectangle) 

# Start the timer
start = time.time()

while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Reduce the image size by half
    frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)

    # Comment out the line that converts the image to grayscale
    # frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    if topLeft_clicked:
        cv2.circle(frame, center=pt1, radius=5, color=(0,0,255), thickness=-1)
        
    #drawing rectangle
    if topLeft_clicked and botRight_clicked:
        # Change the color of the rectangle to red
        cv2.rectangle(frame, pt1, pt2, (0, 0,255), 2)
        
        pts=list([pt1, pt2])
        entrance_pts.append(pts)#np.vstack((entrance_pts, pts))
        
    # Display the resulting frame
    cv2.imshow('Entrance', frame)

    # This command let's us quit with the "q" button on a keyboard.
    # Simply pressing X on the window won't work!
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Stop the timer
end = time.time()

# Calculate the execution time
print(f"Execution time: {end - start} seconds")

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()
entrance_pts=np.unique(entrance_pts,axis=0)
print(entrance_pts)
pickle.dump(entrance_pts, sys.stdout) 


Execution time: 9.81919002532959 seconds
[[[ 79  89]
  [171 185]]

 [[153  48]
  [243 160]]

 [[279  86]
  [319 110]]]
�cnumpy.core.multiarray
_reconstruct
qcnumpy
ndarray
qK�qCbq�qRq(KKKK�qcnumpy
dtype
qXi4���q	Rq
tqb.<qNNNJ����J����Ktqb�C0OY���0��V?nq