In [14]:
import cv2 
import numpy as np
import sys
import pickle

n_ROI=4 # how many ROIs you want to select 

# mouse callback function to select the ROIs
def draw_rectangle(event,x,y,flags,param):

    global pt1,pt2,topLeft_clicked,botRight_clicked

    # get mouse click
    if event == cv2.EVENT_LBUTTONDOWN:

        if topLeft_clicked == True and botRight_clicked == True:
            topLeft_clicked = False
            botRight_clicked = False
            pt1 = (0,0)
            pt2 = (0,0)

        if topLeft_clicked == False:
            pt1 = (x,y)
            topLeft_clicked = True
            
        elif botRight_clicked == False:
            pt2 = (x,y)
            botRight_clicked = True

        
# Haven't drawn anything yet!
reward_pts=list()#np.zeros(2)# 2 because there are 2 points to identify each region
pt1 = (0,0)
pt2 = (0,0)
topLeft_clicked = False
botRight_clicked = False

cap = cv2.VideoCapture(0) # add a 0 to connect to the camera 

# Create a named window for connections
cv2.namedWindow('Test')

# Bind draw_rectangle function to mouse cliks
cv2.setMouseCallback('Test', draw_rectangle) 


while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    if topLeft_clicked:
        cv2.circle(frame, center=pt1, radius=5, color=(0,0,255), thickness=-1)
        
    #drawing rectangle
    if topLeft_clicked and botRight_clicked:
        cv2.rectangle(frame, pt1, pt2, (0, 0, 255), 2)
        
         
        pts=list([pt1, pt2])
        reward_pts.append( pts)
        
    # Display the resulting frame
    cv2.imshow('Test', frame)

    # This command let's us quit with the "q" button on a keyboard.
    # Simply pressing X on the window won't work!
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()
reward_pts=np.unique(reward_pts,axis=0)
print(reward_pts) 
pickle.dump(reward_pts, sys.stdout) 

[[[ 49 135]
  [183 203]]

 [[ 69 307]
  [189 401]]

 [[469 132]
  [593 187]]

 [[487 327]
  [617 405]]]
�cnumpy.core.multiarray
_reconstruct
qcnumpy
ndarray
qK�qCbq�qRq(KKKK�qcnumpy
dtype
qXi4q���q	Rq
tqb.

In [16]:
reward_points=np.unique(reward_pts[1:,],axis=0)
reward_points

    

array([[[ 69, 307],
        [189, 401]],

       [[469, 132],
        [593, 187]],

       [[487, 327],
        [617, 405]]])

In [16]:
cap.release()
cv2.destroyAllWindows()

In [18]:
for i in range(len(reward_pts)):
    print(reward_pts[i])

[[ 49 135]
 [183 203]]
[[ 69 307]
 [189 401]]
[[469 132]
 [593 187]]
[[487 327]
 [617 405]]


array([[253., 341.],
       [282., 370.],
       [253., 341.],
       ...,
       [370., 167.],
       [333., 127.],
       [370., 167.]])

In [1]:
import csv
from tkinter import filedialog as fd

filename = fd.askopenfilename()

with open(filename, "r") as infile:
    reader = csv.DictReader(infile)
    for row in reader:
        print(row)   



OrderedDict([('Trials', 'LL'), ('l', '0'), ('r', '90'), ('ll', '0'), ('lr', '90'), ('rl', '90'), ('rr', '90'), ('ROI1', None), ('ROI2', None), ('ROI3', None), ('ROI4', None)])
OrderedDict([('Trials', 'LR'), ('l', '0'), ('r', '90'), ('ll', '90'), ('lr', '0'), ('rl', '90'), ('rr', '90'), ('ROI1', None), ('ROI2', None), ('ROI3', None), ('ROI4', None)])
OrderedDict([('Trials', 'RL'), ('l', '90'), ('r', '0'), ('ll', '90'), ('lr', '90'), ('rl', '0'), ('rr', '90'), ('ROI1', None), ('ROI2', None), ('ROI3', None), ('ROI4', None)])
OrderedDict([('Trials', 'RR'), ('l', '90'), ('r', '0'), ('ll', '90'), ('lr', '90'), ('rl', '90'), ('rr', '0'), ('ROI1', None), ('ROI2', None), ('ROI3', None), ('ROI4', None)])
OrderedDict([('Trials', 'control'), ('l', '0'), ('r', '0'), ('ll', '0'), ('lr', '0'), ('rl', '0'), ('rr', '0'), ('ROI1', None), ('ROI2', None), ('ROI3', None), ('ROI4', None)])
